PeodeApp/Controllers/KylalisedController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PeodeApp.Data;
using PeodeApp.Models;

namespace PeodeApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class KylalisedController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KylalisedController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Kylalised
        public async Task<IActionResult> Index(List<Kylaline>? kylalised = null)
        {
            if (kylalised == null)
                return View(await _context.Kylalined.ToListAsync());
            else
                return View(kylalised);
        }

        // GET: Kylalised/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kylaline = await _context.Kylalined
                .FirstOrDefaultAsync(m => m.ID == id);
            if (kylaline == null)
            {
                return NotFound();
            }

            return View(kylaline);
        }

        // GET: Kylalised/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kylalised/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nimi,Email,OnKutse,PyhaID")] Kylaline kylaline)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kylaline);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kylaline);
        }

        // GET: Kylalised/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kylaline = await _context.Kylalined.FindAsync(id);
            if (kylaline == null)
            {
                return NotFound();
            }
            return View(kylaline);
        }

        // POST: Kylalised/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nimi,Email,OnKutse,PyhaID")] Kylaline kylaline)
        {
            if (id != kylaline.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kylaline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KylalineExists(kylaline.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kylaline);
        }

        // GET: Kylalised/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kylaline = await _context.Kylalined
                .FirstOrDefaultAsync(m => m.ID == id);
            if (kylaline == null)
            {
                return NotFound();
            }

            return View(kylaline);
        }

        // POST: Kylalised/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kylaline = await _context.Kylalined.FindAsync(id);
            if (kylaline != null)
            {
                _context.Kylalined.Remove(kylaline);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KylalineExists(int id)
        {
            return _context.Kylalined.Any(e => e.ID == id);
        }

        public async Task<IActionResult> Tulevad()
        {
            var tulevad = _context.Kylalined.Where(x => x.OnKutse == true).ToList();
            ViewBag.Filter = "Tulevad külalised";
            return View("Index", tulevad);
        }

        public async Task<IActionResult> MitteTulevad()
        {
            var tulevad = _context.Kylalined.Where(x => x.OnKutse == false).ToList();
            ViewBag.Filter = "Mitte tulevad külalised";
            return View("Index", tulevad);
        }
    }
}

PeodeApp/Controllers/PyhadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PeodeApp.Data;
using PeodeApp.Models;

namespace PeodeApp.Controllers
{
    [Authorize(Roles = "Admin")] // Ainult sisse logitud kasutajale
    public class PyhadController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PyhadController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pyhad
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pyhad.ToListAsync());
        }

        // GET: Pyhad/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyha = await _context.Pyhad
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pyha == null)
            {
                return NotFound();
            }

            return View(pyha);
        }

        // GET: Pyhad/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pyhad/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nimi,Kuupaev")] Pyha pyha)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pyha);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pyha);
        }

        // GET: Pyhad/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyha = await _context.Pyhad.FindAsync(id);
            if (pyha == null)
            {
                return NotFound();
            }
            return View(pyha);
        }

        // POST: Pyhad/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nimi,Kuupaev")] Pyha pyha)
        {
            if (id != pyha.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pyha);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PyhaExists(pyha.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pyha);
        }

        // GET: Pyhad/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyha = await _context.Pyhad
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pyha == null)
            {
                return NotFound();
            }

            return View(pyha);
        }

        // POST: Pyhad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pyha = await _context.Pyhad.FindAsync(id);
            if (pyha != null)
            {
                _context.Pyhad.Remove(pyha);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PyhaExists(int id)
        {
            return _context.Pyhad.Any(e => e.ID == id);
        }
    }
}

PeodeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Peofirma</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeodeApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Peofirma</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Avaleht</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">Meiest</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pyhad" asp-action="Index">Puhad</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kylalised" asp-action="Index">Vastused</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Nikita Litvinenko
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>